-- Add start dates (Continuous Service Date) for all employees
UPDATE employees SET start_date = '2025-08-06' WHERE first_name = 'Aabir' AND last_name = 'Basu';
UPDATE employees SET start_date = '2022-07-25' WHERE first_name = 'Adam' AND last_name = 'Paul';
UPDATE employees SET start_date = '2022-06-20' WHERE first_name = 'Adam' AND last_name = 'Scammell';
UPDATE employees SET start_date = '2018-08-20' WHERE first_name = 'Adam' AND last_name = 'Lichter';
UPDATE employees SET start_date = '2024-09-04' WHERE first_name = 'Alejandro' AND last_name = 'Castanon';
UPDATE employees SET start_date = '2025-08-25' WHERE first_name = 'Alexandre' AND last_name = 'Louis';
UPDATE employees SET start_date = '2025-03-10' WHERE first_name = 'Ameerah' AND last_name = 'Mallam-Hassam';
UPDATE employees SET start_date = '2024-01-04' WHERE first_name = 'Andrew' AND last_name = 'Gaichuk';
UPDATE employees SET start_date = '2017-05-08' WHERE first_name = 'Brandon' AND last_name = 'Bemister';
UPDATE employees SET start_date = '2026-01-05' WHERE first_name = 'Brookes' AND last_name = 'Shean';
UPDATE employees SET start_date = '2026-01-07' WHERE first_name = 'Chukwuemeka (Emeka)' AND last_name = 'Nduka-Nwagbo';
UPDATE employees SET start_date = '2025-08-11' WHERE first_name = 'Cole' AND last_name = 'Inkpen';
UPDATE employees SET start_date = '2024-08-19' WHERE first_name = 'David' AND last_name = 'Murray';
UPDATE employees SET start_date = '2022-01-10' WHERE first_name = 'Devon' AND last_name = 'Hong';
UPDATE employees SET start_date = '2025-12-03' WHERE first_name = 'Donald' AND last_name = 'Gross';
UPDATE employees SET start_date = '2023-09-20' WHERE first_name = 'Douglas (Mark)' AND last_name = 'Simms';
UPDATE employees SET start_date = '2025-06-03' WHERE first_name = 'Elizabeth' AND last_name = 'Somolu';
UPDATE employees SET start_date = '2026-05-06' WHERE first_name = 'Ella' AND last_name = 'Stokes';
UPDATE employees SET start_date = '2020-02-24' WHERE first_name = 'Emily' AND last_name = 'Payne';
UPDATE employees SET start_date = '2022-04-04' WHERE first_name = 'Esteban' AND last_name = 'Ricalde-Gonzalez';
UPDATE employees SET start_date = '2019-07-04' WHERE first_name = 'Freddie' AND last_name = 'Rose';
UPDATE employees SET start_date = '2020-03-02' WHERE first_name = 'Graham' AND last_name = 'Smith';
UPDATE employees SET start_date = '2022-05-09' WHERE first_name = 'Guilherme (Daniel)' AND last_name = 'Correa Danielski';
UPDATE employees SET start_date = '2025-08-18' WHERE first_name = 'Harkirat (Keerat)' AND last_name = 'Kaur';
UPDATE employees SET start_date = '2022-04-11' WHERE first_name = 'Iain' AND last_name = 'Robertson';
UPDATE employees SET start_date = '2024-07-22' WHERE first_name = 'Javier' AND last_name = 'Ortiz Castro';
UPDATE employees SET start_date = '2024-02-12' WHERE first_name = 'Jennifer' AND last_name = 'Collins';
UPDATE employees SET start_date = '2018-05-28' WHERE first_name = 'Jennifer' AND last_name = 'Squires';
UPDATE employees SET start_date = '2017-02-13' WHERE first_name = 'John' AND last_name = 'Hawley';
UPDATE employees SET start_date = '2019-06-17' WHERE first_name = 'John' AND last_name = 'Barrett';
UPDATE employees SET start_date = '2016-07-11' WHERE first_name = 'Joshua' AND last_name = 'Green';
UPDATE employees SET start_date = '2022-10-11' WHERE first_name = 'Joshua' AND last_name = 'Bennett';
UPDATE employees SET start_date = '2022-10-24' WHERE first_name = 'Kar-Wing' AND last_name = 'Lo';
UPDATE employees SET start_date = '2020-11-18' WHERE first_name = 'Kim' AND last_name = 'Drover';
UPDATE employees SET start_date = '2025-08-15' WHERE first_name = 'Lamine (Mohamed)' AND last_name = 'Rabei';
UPDATE employees SET start_date = '2024-10-07' WHERE first_name = 'Leah' AND last_name = 'Sexton';
UPDATE employees SET start_date = '2022-07-04' WHERE first_name = 'Leigh' AND last_name = 'Chalker';
UPDATE employees SET start_date = '2019-04-15' WHERE first_name = 'Maria' AND last_name = 'Miskell';
UPDATE employees SET start_date = '2022-07-11' WHERE first_name = 'Mark' AND last_name = 'Smit';
UPDATE employees SET start_date = '2022-02-21' WHERE first_name = 'Mark' AND last_name = 'Carberry';
UPDATE employees SET start_date = '2016-11-07' WHERE first_name = 'Matthew' AND last_name = 'Kennedy';
UPDATE employees SET start_date = '2021-04-01' WHERE first_name = 'Megan' AND last_name = 'Cooze';
UPDATE employees SET start_date = '2020-01-07' WHERE first_name = 'Melanie' AND last_name = 'Kung';
UPDATE employees SET start_date = '2025-08-06' WHERE first_name = 'Melissa' AND last_name = 'Jeudy';
UPDATE employees SET start_date = '2023-11-27' WHERE first_name = 'Meredith' AND last_name = 'Mumby';
UPDATE employees SET start_date = '2018-06-04' WHERE first_name = 'Michael' AND last_name = 'Hanlon';
UPDATE employees SET start_date = '2018-02-19' WHERE first_name = 'Michael' AND last_name = 'Mitchell';
UPDATE employees SET start_date = '2021-05-27' WHERE first_name = 'Mira' AND last_name = 'Chaya';
UPDATE employees SET start_date = '2022-09-28' WHERE first_name = 'Nico' AND last_name = 'Boehme';
UPDATE employees SET start_date = '2020-07-06' WHERE first_name = 'Nicole' AND last_name = 'Duffett';
UPDATE employees SET start_date = '2026-01-07' WHERE first_name = 'Olivia' AND last_name = 'Verge';
UPDATE employees SET start_date = '2018-01-08' WHERE first_name = 'Peter' AND last_name = 'Woodman';
UPDATE employees SET start_date = '2025-06-03' WHERE first_name = 'Precious' AND last_name = 'Eboreime';
UPDATE employees SET start_date = '2022-08-15' WHERE first_name = 'Rahul' AND last_name = 'Nandakumar';
UPDATE employees SET start_date = '2024-10-28' WHERE first_name = 'Sadaf' AND last_name = 'Mozaffari';
UPDATE employees SET start_date = '2021-10-21' WHERE first_name = 'Sarah' AND last_name = 'Ozon';
UPDATE employees SET start_date = '2021-08-25' WHERE first_name = 'Sharon' AND last_name = 'Janes';
UPDATE employees SET start_date = '2020-03-23' WHERE first_name = 'Shibo (Frank)' AND last_name = 'Nie';
UPDATE employees SET start_date = '2017-01-08' WHERE first_name = 'Shikan (Kan)' AND last_name = 'Yue';
UPDATE employees SET start_date = '2022-01-10' WHERE first_name = 'Siobhan' AND last_name = 'Coady';
UPDATE employees SET start_date = '2022-03-01' WHERE first_name = 'Stephen' AND last_name = 'Collins';
UPDATE employees SET start_date = '2020-12-09' WHERE first_name = 'Stephen' AND last_name = 'Piercey';
UPDATE employees SET start_date = '2019-08-19' WHERE first_name = 'Steve' AND last_name = 'O''Keefe';
UPDATE employees SET start_date = '2022-08-15' WHERE first_name = 'Tamer' AND last_name = 'Shafik';
UPDATE employees SET start_date = '2019-08-28' WHERE first_name = 'Tanner' AND last_name = 'Coombs';
UPDATE employees SET start_date = '2025-11-24' WHERE first_name = 'Uzo' AND last_name = 'Okonkwo';
UPDATE employees SET start_date = '2025-06-23' WHERE first_name = 'Victoria' AND last_name = 'Stokes';
UPDATE employees SET start_date = '2026-03-02' WHERE first_name = 'Vincent' AND last_name = 'Rousseau';
UPDATE employees SET start_date = '2025-05-05' WHERE first_name = 'Youngeun (Joey)' AND last_name = 'Kim';
UPDATE employees SET start_date = '2016-07-11' WHERE first_name = 'Zachary' AND last_name = 'Green';
UPDATE employees SET start_date = '2026-01-06' WHERE first_name = 'Zachary' AND last_name = 'Coffey';
UPDATE employees SET start_date = '2026-01-05' WHERE first_name = 'Zoya' AND last_name = 'Zaidi';
UPDATE employees SET start_date = '2025-02-03' WHERE first_name = 'Zuber' AND last_name = 'Ahmed';
